<?php
$_product = $this->getProduct(); 
$_product_image_url = NULL;

// Check to see if we have an image for this product.
foreach ($_product->getMediaGalleryImages() as $_product_image) {
    if (!$_product_image->getDisabled()) {
		$_product_image_url = $_product_image->getUrl();
		break;
    }
}
?>
<script text="text/javascript">
  var _learnq = _learnq || [];
 
  _learnq.push(['track', 'Viewed Product', {
    Name: "<?php echo $_product->getName(); ?>",
    SKU: "<?php echo $_product->getSku(); ?>",
    Url: "<?php echo $_product->getProductUrl(); ?>",
    <?php if ($_product_image_url) { ?>ImageUrl: "<?php echo $_product_image_url; ?>", <?php } ?>
    Categories: <?php echo $this->getProductCategoriesAsJson(); ?>
  }]);
</script>